services:
  sc-config-server:
    container_name: sc-config-server
    image: kappa9/config-server:1.0.0
    healthcheck:
      test: curl -m 2 --silent --fail --request GET http://localhost:8888/actuator/health
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    ports:
      - "8888:8888"
  sc-discovery-server:
    container_name: sc-discovery-server
    healthcheck:
      test: curl -m 2 --silent --fail --request GET http://localhost:8761/actuator/health
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    depends_on:
      sc-config-server:
        condition: service_healthy
    image: kappa9/discovery-server:1.0.0
    ports:
      - "8761:8761"
  sc-api-gateway:
    container_name: sc-api-gateway
    depends_on:
      sc-config-server:
        condition: service_healthy
      sc-discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://sc-config-server:8888
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: DEBUG
    image: kappa9/api-gateway:1.0.0
    ports:
      - "8080:8080"
  sc-product-service:
    container_name: sc-product-service
    depends_on:
      sc-product-service-postgres:
        condition: service_healthy
      sc-config-server:
        condition: service_healthy
      sc-discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://sc-config-server:8888
    image: kappa9/product-service:1.0.0
    ports:
      - "8081:8081"
  sc-inventory-service:
    container_name: sc-inventory-service
    depends_on:
      sc-config-server:
        condition: service_healthy
      sc-discovery-server:
        condition: service_healthy
      sc-inventory-service-postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://sc-config-server:8888
    image: kappa9/inventory-service:1.0.0
    ports:
      - "8082:8082"
  sc-order-service:
    container_name: sc-order-service
    depends_on:
      sc-config-server:
        condition: service_healthy
      sc-discovery-server:
        condition: service_healthy
      sc-order-service-postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://sc-config-server:8888
    image: kappa9/order-service:1.0.0
    ports:
      - "8083:8083"
  sc-product-service-postgres:
    container_name: sc-product-service-postgres
    image: postgres:14.22
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product_db
    volumes:
      - sc-product-service-db-data:/var/lib/postgresql/data
  sc-inventory-service-postgres:
    container_name: sc-inventory-service-postgres
    image: postgres:14.22
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory_db
    volumes:
      - sc-inventory-service-db-data:/var/lib/postgresql/data
  sc-order-service-postgres:
    container_name: sc-order-service-postgres
    image: postgres:14.22
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_db
    volumes:
      - sc-order-service-db-data:/var/lib/postgresql/data
volumes:
  sc-product-service-db-data:
  sc-inventory-service-db-data:
  sc-order-service-db-data:
